# Generated by Django 5.2.9 on 2026-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(db_index=True)),
                ('exam_date', models.DateField(db_index=True)),
                ('subject', models.CharField(db_index=True, max_length=64)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('wrong', models.PositiveIntegerField(default=0)),
                ('blank', models.PositiveIntegerField(default=0)),
                ('net', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['student_id', 'exam_date'], name='students_ex_student_ed5435_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_id', 'exam_date', 'subject'), name='uniq_examresult_student_date_subject')],
            },
        ),
    ]
