# Generated by Django 5.2.9 on 2026-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('grade', models.PositiveSmallIntegerField(default=8)),
                ('target_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ('-exam_date', 'subject')},
        ),
        migrations.RemoveConstraint(
            model_name='examresult',
            name='uniq_examresult_student_date_subject',
        ),
        migrations.RemoveIndex(
            model_name='examresult',
            name='students_ex_student_ed5435_idx',
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student_id', 'exam_date', 'subject')},
        ),
        migrations.AlterField(
            model_name='examresult',
            name='blank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='net',
        ),
    ]
