# Generated by Django 5.2.9 on 2026-01-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_alter_examresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-exam_date', 'subject']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='examresult',
            name='net',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='subject',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('subject', models.CharField(blank=True, default='', max_length=64)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('topic_name', models.CharField(blank=True, default='', max_length=255)),
                ('task_type', models.CharField(default='practice', max_length=32)),
                ('question_count', models.IntegerField(default=0)),
                ('recommended_seconds', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.student')),
            ],
            options={
                'ordering': ['date', 'order', 'id'],
                'indexes': [models.Index(fields=['student', 'date'], name='students_st_student_52ac25_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField()),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('blank', models.IntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
