# Generated by Django 5.2.9 on 2026-01-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_examresult_options_remove_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_group',
            field=models.CharField(blank=True, default='LGS', max_length=20),
        ),
    ]
