# Generated by Django 5.2.9 on 2026-01-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_exam_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LGS', 'LGS (Liselere Geçiş Sistemi)'), ('YKS_TYT', 'YKS - TYT (Temel Yeterlilik)'), ('YKS_AYT_SAY', 'YKS - AYT (Sayısal)'), ('YKS_AYT_EA', 'YKS - AYT (Eşit Ağırlık)'), ('YKS_AYT_SOZ', 'YKS - AYT (Sözel)'), ('YKS_AYT_DIL', 'YKS - AYT (Dil)')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_study_seconds', models.IntegerField(default=7200)),
                ('focus_subjects', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_config', to='students.student')),
                ('primary_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching.examtype')),
            ],
        ),
    ]
