# Generated by Django 5.2.9 on 2026-01-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_subject_topic_studentprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingconfig',
            name='focus_subjects',
        ),
        migrations.AddField(
            model_name='coachingconfig',
            name='current_academic_month',
            field=models.IntegerField(blank=True, help_text='Current focused calendar month (e.g. 9 for Sept)', null=True),
        ),
        migrations.AddField(
            model_name='coachingconfig',
            name='current_academic_week',
            field=models.IntegerField(blank=True, help_text='Current focused week within the month (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='coachingconfig',
            name='week_started_at',
            field=models.DateField(blank=True, help_text='The date when the student started this academic week', null=True),
        ),
    ]
