# Generated by Django 5.2.9 on 2026-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_remove_coachingconfig_focus_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingconfig',
            name='last_coach_message',
            field=models.TextField(blank=True, default='', help_text='Latest motivational message from AI'),
        ),
    ]
